apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workshop
  name: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:alpine3.20
        name: nginx
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: index
        secret:
          secretName: whoop